name: Lint GitHub Workflows

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1
        with:
          fail-on-error: true